backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "hero"
    label: "Hero Slider"
    files:
      - name: "slides"
        label: "Slides"
        file: "content/hero/slider.yml"
        fields:
          - label: "Slides"
            name: "slides"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: string }
              - { label: "Subtitle", name: "subtitle", widget: string }
              - { label: "Image", name: "image", widget: image }